/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.grupo1.deremate.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param destination 
 * @param userId 
 */


data class CreateRouteDTO (

    @SerializedName("destination")
    val destination: kotlin.String? = null,

    @SerializedName("userId")
    val userId: kotlin.Long? = null

) {


}

