/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.grupo1.deremate.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param message 
 * @param `data` 
 */


data class GenericResponseDTO (

    @SerializedName("message")
    val message: kotlin.String? = null,

    @SerializedName("data")
    val `data`: kotlin.Any? = null

) {


}

