/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.grupo1.deremate.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param token 
 * @param expiresIn 
 */


data class LoginResponseDTO (

    @SerializedName("token")
    val token: kotlin.String? = null,

    @SerializedName("expiresIn")
    val expiresIn: kotlin.Long? = null

) {


}

