/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.grupo1.deremate.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param status 
 * @param packageLocation 
 */


data class PackageInWarehouseDTO (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("status")
    val status: kotlin.String? = null,

    @SerializedName("packageLocation")
    val packageLocation: kotlin.String? = null

) {


}

