/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.grupo1.deremate.models

import com.grupo1.deremate.models.SortObject

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param offset 
 * @param sort 
 * @param pageNumber 
 * @param paged 
 * @param unpaged 
 * @param pageSize 
 */


data class PageableObject (

    @SerializedName("offset")
    val offset: kotlin.Long? = null,

    @SerializedName("sort")
    val sort: SortObject? = null,

    @SerializedName("pageNumber")
    val pageNumber: kotlin.Int? = null,

    @SerializedName("paged")
    val paged: kotlin.Boolean? = null,

    @SerializedName("unpaged")
    val unpaged: kotlin.Boolean? = null,

    @SerializedName("pageSize")
    val pageSize: kotlin.Int? = null

) {


}

