/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.grupo1.deremate.models

import com.grupo1.deremate.models.PageableObject
import com.grupo1.deremate.models.PointsDTO
import com.grupo1.deremate.models.SortObject

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param totalElements 
 * @param totalPages 
 * @param first 
 * @param last 
 * @param propertySize 
 * @param content 
 * @param number 
 * @param sort 
 * @param pageable 
 * @param numberOfElements 
 * @param empty 
 */


data class PagePointsDTO (

    @SerializedName("totalElements")
    val totalElements: kotlin.Long? = null,

    @SerializedName("totalPages")
    val totalPages: kotlin.Int? = null,

    @SerializedName("first")
    val first: kotlin.Boolean? = null,

    @SerializedName("last")
    val last: kotlin.Boolean? = null,

    @SerializedName("size")
    val propertySize: kotlin.Int? = null,

    @SerializedName("content")
    val content: kotlin.collections.List<PointsDTO>? = null,

    @SerializedName("number")
    val number: kotlin.Int? = null,

    @SerializedName("sort")
    val sort: SortObject? = null,

    @SerializedName("pageable")
    val pageable: PageableObject? = null,

    @SerializedName("numberOfElements")
    val numberOfElements: kotlin.Int? = null,

    @SerializedName("empty")
    val empty: kotlin.Boolean? = null

) {


}

