/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.grupo1.deremate.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param userId 
 * @param points 
 * @param lastUpdated 
 * @param tierName 
 * @param active 
 */


data class PointsDTO (

    @SerializedName("userId")
    val userId: kotlin.Long? = null,

    @SerializedName("points")
    val points: kotlin.Int? = null,

    @SerializedName("lastUpdated")
    val lastUpdated: java.time.OffsetDateTime? = null,

    @SerializedName("tierName")
    val tierName: kotlin.String? = null,

    @SerializedName("active")
    val active: kotlin.Boolean? = null

) {


}

