/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.grupo1.deremate.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param totalUsers 
 * @param totalPoints 
 * @param averagePoints 
 * @param medianPoints 
 * @param maxPoints 
 * @param minPoints 
 * @param usersWithZeroPoints 
 */


data class PointsStatisticsDTO (

    @SerializedName("totalUsers")
    val totalUsers: kotlin.Int? = null,

    @SerializedName("totalPoints")
    val totalPoints: kotlin.Int? = null,

    @SerializedName("averagePoints")
    val averagePoints: kotlin.Double? = null,

    @SerializedName("medianPoints")
    val medianPoints: kotlin.Int? = null,

    @SerializedName("maxPoints")
    val maxPoints: kotlin.Int? = null,

    @SerializedName("minPoints")
    val minPoints: kotlin.Int? = null,

    @SerializedName("usersWithZeroPoints")
    val usersWithZeroPoints: kotlin.Int? = null

) {


}

