/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.grupo1.deremate.models


import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param price 
 */


data class ProductDTO (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("description")
    val description: kotlin.String? = null,

    @SerializedName("price")
    val price: java.math.BigDecimal? = null

): Serializable {


}

