/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.grupo1.deremate.models


import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * 
 *
 * @param id 
 * @param origin 
 * @param destination 
 * @param status 
 * @param completedAt 
 * @param assignedToEmail 
 */


data class RouteDTO (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("origin")
    val origin: kotlin.String? = null,

    @SerializedName("destination")
    val destination: kotlin.String? = null,

    @SerializedName("status")
    val status: RouteDTO.Status? = null,

    @SerializedName("completedAt")
    val completedAt: String? = null,

    @SerializedName("assignedToEmail")
    val assignedToEmail: kotlin.String? = null

): Serializable {

    /**
     * 
     *
     * Values: PENDING,INITIATED,COMPLETED
     */
    enum class Status(val value: kotlin.String) {
        @SerializedName(value = "PENDING") PENDING("PENDING"),
        @SerializedName(value = "INITIATED") INITIATED("INITIATED"),
        @SerializedName(value = "COMPLETED") COMPLETED("COMPLETED");
    }

}

