/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.grupo1.deremate.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param email 
 * @param firstname 
 * @param lastname 
 */


data class UserDTO (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("email")
    val email: kotlin.String? = null,

    @SerializedName("firstname")
    val firstname: kotlin.String? = null,

    @SerializedName("lastname")
    val lastname: kotlin.String? = null,

    @SerializedName("isEmailVerified")
    val isEmailVerified: kotlin.Boolean? = null

) {


}

